### ISSUE TITLE
적의 움직임을 Character Movement 를 통해 움직이기

### ISSUE THREAD

**Issue by Arialari** [Arialari/Gratuation_Project#10]
패턴을 쉽게 쉽게 넣을 수 있게 하려고 합니당

**Comment by Arialari** [comment]
타임라인을 넣어보려고 했는데 타임라인의 키와 외부커브들을 변수화 할 수 있는 방법을 찾지 못했습니다
혹시 아시는분 계신가요?

**Comment by MasterJoin** [comment]
상황을 알수없어.
상황을 묘사할 그림이 필요.

2018. 2. 25. 오후 2:48에 "애리" <notifications@github.com>님이 작성:

**Comment by MasterJoin** [comment]
@Arialari

**Comment by Arialari** [comment]
결국 어떻게든 해냈습니다 ☆
