### ISSUE TITLE
다음 레벨로 변수값 넘기기

### ISSUE THREAD

**Issue by Arialari** [Arialari/Gratuation_Project#15]
다음 레벨로 변수가 안넘어가서.. 일단 무기한 연기

**Comment by MasterJoin** [comment]
레벨  넘기는 방법은 기본적으로는 두가지가 있다.
필요함 사무실로와서 물어봐 알려줄게.

2018년 4월 1일 (일) 오후 11:27, 애리 <notifications@github.com>님이 작성:
